defaults: &defaults
  google_account_id: 

development:
  <<: *defaults
  paperclip:
    # LOCAL CONFIG:
    storage: :filesystem
    # S3 CONFIG:
    #storage: :s3
    #path: "report/:attachment/:key.:extension"
    #s3_credentials:
      #bucket: us.assets.dev.hrtapp.com
      #access_key_id: <%= ENV['AMAZON_ACCESS_KEY_ID'] %>
      #secret_access_key: <%= ENV['AMAZON_SECRET_ACCESS_KEY'] %>
    #s3_permissions: public-read

test:
  <<: *defaults
  paperclip:
    storage: :filesystem

cucumber:
  <<: *defaults
  paperclip:
    storage: :filesystem

staging:
  <<: *defaults
  paperclip:
    path: "report/:attachment/:key.:extension"
    storage: :s3
    s3_credentials:
      bucket: us.assets.staging.hrtapp.com
      access_key_id: <%= ENV['AMAZON_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['AMAZON_SECRET_ACCESS_KEY'] %>
    s3_permissions: public-read

production:
  <<: *defaults
  google_account_id: UA-22139528-1
  paperclip:
    path: "report/:attachment/:key.:extension"
    storage: :s3
    s3_credentials:
      bucket: us.assets.hrtapp.com
      access_key_id: <%= ENV['AMAZON_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['AMAZON_SECRET_ACCESS_KEY'] %>
    s3_permissions: public-read
